server.port=9090
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=stat
spring.datasource.password=stat